sudo: required

language: php

services:
  - docker

matrix:
    fast_finish: true
    include:
        #
        # Define versions of MySQL and MariaDB to test against.
        #
        # For each DB version also tests with different adapters are run (mysqli, PDO).
        #
        #
        # mysql 5.7
        #
        - php: 7.2
          env: DB=mysql:5.7 DB_ADAPTER=mysqli
        - php: 7.2
          env: DB=mysql:5.7 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.2
          env: DB=mysql:5.7 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.3
          env: DB=mysql:5.7 DB_ADAPTER=mysqli
        - php: 7.3
          env: DB=mysql:5.7 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.3
          env: DB=mysql:5.7 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.4
          env: DB=mysql:5.7 DB_ADAPTER=mysqli
        - php: 7.4
          env: DB=mysql:5.7 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.4
          env: DB=mysql:5.7 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        #
        # mariadb 10.1
        #
        - php: 7.2
          env: DB=mariadb:10.1 DB_ADAPTER=mysqli
        - php: 7.2
          env: DB=mariadb:10.1 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.2
          env: DB=mariadb:10.1 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.3
          env: DB=mariadb:10.1 DB_ADAPTER=mysqli
        - php: 7.3
          env: DB=mariadb:10.1 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.3
          env: DB=mariadb:10.1 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.4
          env: DB=mariadb:10.1 DB_ADAPTER=mysqli
        - php: 7.4
          env: DB=mariadb:10.1 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.4
          env: DB=mariadb:10.1 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        #
        # mariadb 10.2
        #
        - php: 7.2
          env: DB=mariadb:10.2 DB_ADAPTER=mysqli
        - php: 7.2
          env: DB=mariadb:10.2 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.2
          env: DB=mariadb:10.2 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.3
          env: DB=mariadb:10.2 DB_ADAPTER=mysqli
        - php: 7.3
          env: DB=mariadb:10.2 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.3
          env: DB=mariadb:10.2 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.4
          env: DB=mariadb:10.2 DB_ADAPTER=mysqli
        - php: 7.4
          env: DB=mariadb:10.2 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.4
          env: DB=mariadb:10.2 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        #
        # mariadb 10.3
        #
        - php: 7.2
          env: DB=mariadb:10.3 DB_ADAPTER=mysqli
        - php: 7.2
          env: DB=mariadb:10.3 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.2
          env: DB=mariadb:10.3 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.3
          env: DB=mariadb:10.3 DB_ADAPTER=mysqli
        - php: 7.3
          env: DB=mariadb:10.3 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.3
          env: DB=mariadb:10.3 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.4
          env: DB=mariadb:10.3 DB_ADAPTER=mysqli
        - php: 7.4
          env: DB=mariadb:10.3 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.4
          env: DB=mariadb:10.3 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        #
        # mariadb 10.4
        #
        - php: 7.2
          env: DB=mariadb:10.4 DB_ADAPTER=mysqli
        - php: 7.2
          env: DB=mariadb:10.4 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.2
          env: DB=mariadb:10.4 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.3
          env: DB=mariadb:10.4 DB_ADAPTER=mysqli
        - php: 7.3
          env: DB=mariadb:10.4 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.3
          env: DB=mariadb:10.4 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.4
          env: DB=mariadb:10.4 DB_ADAPTER=mysqli
        - php: 7.4
          env: DB=mariadb:10.4 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.4
          env: DB=mariadb:10.4 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        #
        # mariadb 10.5
        #
        - php: 7.2
          env: DB=mariadb:10.5 DB_ADAPTER=mysqli
        - php: 7.2
          env: DB=mariadb:10.5 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.2
          env: DB=mariadb:10.5 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.3
          env: DB=mariadb:10.5 DB_ADAPTER=mysqli
        - php: 7.3
          env: DB=mariadb:10.5 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.3
          env: DB=mariadb:10.5 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
        - php: 7.4
          env: DB=mariadb:10.5 DB_ADAPTER=mysqli
        - php: 7.4
          env: DB=mariadb:10.5 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql
        - php: 7.4
          env: DB=mariadb:10.5 DB_ADAPTER=pdo DB_PDO_PROTOCOL=mysql CACHE_ENABLED=true
git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
    #
    # install and init database (see matrix => include => env)
    #
    - ./.travis/install-and-init-db.sh

    #
    # setup and run tests
    #
    # Install composer packages, will also trigger dump-autoload
    - travis_retry composer install --no-interaction --prefer-dist
    # Install coveralls.phar
    - travis_retry wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.1.0/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version

script:
    - vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_success:
    # Submit coverage report to Coveralls servers, see .coveralls.yml
    - travis_retry php coveralls.phar -v
